USE [master]
GO

/****** Object:  Database [PruebaIntergrupo]    Script Date: 21/02/2021 8:33:43 a. m. ******/
CREATE DATABASE [PruebaIntergrupo]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PruebaIntergrupo', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PruebaIntergrupo.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PruebaIntergrupo_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PruebaIntergrupo_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PruebaIntergrupo].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PruebaIntergrupo] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET ARITHABORT OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PruebaIntergrupo] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PruebaIntergrupo] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PruebaIntergrupo] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PruebaIntergrupo] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PruebaIntergrupo] SET  MULTI_USER 
GO

ALTER DATABASE [PruebaIntergrupo] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PruebaIntergrupo] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PruebaIntergrupo] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PruebaIntergrupo] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PruebaIntergrupo] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PruebaIntergrupo] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PruebaIntergrupo] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PruebaIntergrupo] SET  READ_WRITE 
GO

